export const SHOP_CATEGORIES = [
  { value: 'electronics', label: 'Electronics' },
  { value: 'clothing', label: 'Clothing & Fashion' },
  { value: 'home-garden', label: 'Home & Garden' },
  { value: 'sports-outdoors', label: 'Sports & Outdoors' },
  { value: 'books-media', label: 'Books & Media' },
  { value: 'health-beauty', label: 'Health & Beauty' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'toys-games', label: 'Toys & Games' },
  { value: 'food-beverage', label: 'Food & Beverage' },
  { value: 'jewelry-accessories', label: 'Jewelry & Accessories' },
  { value: 'pet-supplies', label: 'Pet Supplies' },
  { value: 'office-supplies', label: 'Office Supplies' },
  { value: 'crafts-hobbies', label: 'Crafts & Hobbies' },
  { value: 'musical-instruments', label: 'Musical Instruments' },
  { value: 'art-collectibles', label: 'Art & Collectibles' },
  { value: 'industrial-scientific', label: 'Industrial & Scientific' },
  { value: 'other', label: 'Other' },
];
